name: betterrank
description: Cool ranking app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.3
  firebase_core: ^2.7.1
  firebase_auth: ^4.2.10
  go_router: ^6.5.1
  google_fonts: ^4.0.3
  intl: ^0.17.0
  sign_in_with_apple: ^4.3.0
  google_sign_in: ^6.0.2
  get_it: ^7.2.0
  injectable: ^2.1.0
  cloud_firestore: ^4.4.4
  image_picker: ^0.8.7
  permission_handler: ^10.2.0
  lottie: ^2.3.0
  firebase_storage: ^11.0.16

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.2.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/anim/